### ISSUE TITLE
formatRemotePath return //.folder 

### ISSUE THREAD

**Issue by F0xtr0t** [tiezhu92/faster-webpack-upload-plugin#4]
Hello everyone,

I have an issue when plugin uploading folders to the remote ftp.

Folder name is not correctly generated in "formatRemotePath". Ex : **/assets//.css** instead of **/assets/css**

In my example, a simple console log in the "getFolderNFiles" function allows you to see that the "file" paths from "assets" are in the format: **../css/theme.css** and the remotePath: **/home/www/assets/**

Other example :  **/assets//.fonts** instead of **/assets/fonts** (subfolder are not impacted by this issue)

The results on the ftp are : **assets/.fonts/(somes files)** and **assets/.css/theme.css**

Additionally, the "js" folder seems to be ignored. Thus the "/js/theme.js" file is placed directly at the root of "assets" instead of being uploaded in the js subfolder.

Configuration input/output webpack : 

`
entry: path.join(__dirname, '_dev/js/index.js'),
output: {
    path: path.join(__dirname, 'assets/js/'),
    filename: 'theme.js'
  },
`

Plugins used in parallel : MiniCssExtractPlugin, CopyPlugin

`
new CopyPlugin({
      patterns: [
        { from: path.join(__dirname, '_dev/img'), to: path.join(__dirname, 'assets/img'), force: true },
        { from: path.join(__dirname, '_dev/fonts'), to: path.join(__dirname, 'assets/fonts'), force: true }
      ]
    })
`
and
`
new MiniCssExtractPlugin({
      filename: "../css/theme.css",
      chunkFilename: "[id].css",
    });
`
Is it due to my configuration or is it a bug ?

**Comment by tiezhu92** [comment]
Thank you for your issure！
I'm sorry I'm so slow in replying, it‘s will fix soon
